# syntax=docker/dockerfile:1
FROM node:20-alpine AS deps
WORKDIR /app
# The schema must be present before `npm ci`: the postinstall hook runs `prisma generate`,
# which exits 1 if it cannot find prisma/schema.prisma. Copying it here also keeps this
# layer cached on source-only changes.
COPY package.json package-lock.json prisma.config.ts ./
COPY prisma ./prisma
RUN npm ci

FROM node:20-alpine AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# The client is already generated by the deps stage's postinstall; regenerate anyway so a
# schema change in the copied source can never be served by a stale cached client.
RUN npx prisma generate
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN addgroup -S app && adduser -S app -G app
COPY --from=build /app/public ./public
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static
USER app
EXPOSE 3000
CMD ["node", "server.js"]
