# syntax=docker/dockerfile:1
# Четыре стадии. Запуск одной командой (ТЗ §4.2.3): `docker compose up --build`,
# см. docker-compose.yml. Без --target собирается последняя стадия (runner), так что
# `docker build -t rrp .` по-прежнему даёт образ приложения.
#   deps    — зависимости (npm ci) и сгенерированный клиент Prisma;
#   migrate — разовый прогон миграций и сева; в compose это сервис migrate;
#   build   — next build в standalone-вывод;
#   runner  — минимальный образ приложения, без Prisma CLI, tsx и исходников.
FROM node:20-alpine AS deps
WORKDIR /app
# The schema must be present before `npm ci`: the postinstall hook runs `prisma generate`,
# which exits 1 if it cannot find prisma/schema.prisma. Copying it here also keeps this
# layer cached on source-only changes.
COPY package.json package-lock.json prisma.config.ts ./
COPY prisma ./prisma
RUN npm ci

# Миграции и сев. Стадия наследует deps целиком: в ней есть Prisma CLI, tsx и dotenv из
# devDependencies, а клиент Prisma уже сгенерирован postinstall-хуком по той же схеме.
# `next build` здесь не нужен, поэтому стадия собирается быстро и не зависит от build.
# DATABASE_URL и пароли демо-аккаунтов приходят из окружения (docker-compose.yml).
# Сев идемпотентен, поэтому повторный `docker compose up` безопасен.
FROM deps AS migrate
WORKDIR /app
COPY . .
CMD ["sh", "-c", "npx prisma migrate deploy && npx tsx scripts/seed.ts"]

FROM node:20-alpine AS build
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# The client is already generated by the deps stage's postinstall; regenerate anyway so a
# schema change in the copied source can never be served by a stale cached client.
RUN npx prisma generate
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
# HOSTNAME=0.0.0.0 обязателен: Docker сам кладёт в HOSTNAME id контейнера, и standalone-сервер
# слушал бы только этот адрес — тогда проверка здоровья изнутри контейнера на 127.0.0.1 падает.
ENV HOSTNAME=0.0.0.0 PORT=3000 NEXT_TELEMETRY_DISABLED=1
RUN addgroup -S app && adduser -S app -G app
COPY --from=build /app/public ./public
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static
USER app
EXPOSE 3000
CMD ["node", "server.js"]
